version: "3.9"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./databace:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  server:
    build: ./node-xepress-crud
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      db_host: db
      db_user: root
      db_password: 1234
      db_database: mydb
      db_port: 3306

  front:
    build: ./ReactNumer
    ports:
      - "5173:5173"
    depends_on:
      - server
